/*MIT License
*
*Copyright (c) 2018 Alysson Ribeiro da Silva
*
*Permission is hereby granted, free of charge, to any person obtaining a copy 
*of this software and associated documentation files (the "Software"), to deal 
*in the Software without restriction, including *without limitation the rights 
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
*copies of the Software, and to permit persons to whom the Software is furnished 
*to do so, subject *to the following conditions:
*
*The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*
*THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
*EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. *IN NO EVENT SHALL THE AUTHORS 
*OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN 
*AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH 
*THE *SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef ARSIMAGE_H
#define ARSIMAGE_H

//--------------------------LOCAL INCLUDES------------------------

//--------------------------GLOBAL INCLUDES-----------------------

//--------------------------MACROS--------------------------------

//--------------------------DIRECTIVES----------------------------

/*
 * ArsImage class - Can be used to store info. about 2D images.
 *
 * version
 *		1.0 25 August 2014
 *
 * author
 *		Alysson Silva
 */
class ArsImage
{
public:
    /**
     * Default constructor, can be used to create an instance of this object.
     */
    ArsImage(const char* fileName);

    /**
     * Default destructor, can be used to destroy this object.
     */
    ~ArsImage(void);

    /*
     * method <getId>
     * param  <>
     * description <Return texture ID>
     */
    int getId();

    /*
     * method <getWidth>
     * param  <>
     * description <Return texture width>
     */
    int getWidth();

    /*
     * method <getHeight>
     * param  <>
     * description <Return texture height>
     */
    int getHeight();

    /*
     * method <getFormat>
     * param  <>
     * description <Return texture format>
     */
    int getFormat();

    /*
     * method <getData>
     * param  <>
     * description <Return texture data>
     */
    void* getData();

private:
    /* Utilized to store the image id generated by the DevIL library */
    int id;

    /* width of the image */
    int width;

    /* height of the image */
    int height;

    /* format of the image */
    int format;

    /* type of the image */
    int type;

    /* Image data */
    void* data;
};
#endif

